### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by BlackIQ** [arman324/Secure-Banking-System#1]
Hi,

In README you named libraries. But what about having a requirements file?
I think if there be a requirements file is better for installation and development. Anyway, this is just a suggestion.

Live long and prosper.
Amir.

P.S: I am not so good in English. Sorry if there is grammar problem.

**Comment by arman324** [comment]
Dear Amir, 

Thanks for you feedback.

Best regards,
Arman
